checksum jbr

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -109,7 +109,7 @@ jobs:
         if: '${{ ((matrix.os == ''macos'')) && (!(matrix.selfHosted)) }}'
       - id: 'step-2'
         name: 'Get JBR 21 for macOS AArch64'
-        run: 'wget https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz -O ${{ runner.temp }}/jbr21.tar.gz && file ${{ runner.temp }}/jbr21.tar.gz'
+        run: "\n        checksum_url=\"https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz.checksum\"\n        expected_checksum=$(wget -q -O - $checksum_url)\n        file_checksum=\"\"\n        if [ -f ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz ]; then\n            file_checksum=$(shasum -a 256 ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz | awk '{print $1}')\n        fi\n        if [ \"$file_checksum\" != \"$expected_checksum\" ]; then\n            wget -q --tries=3 https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz -O ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz\n            file_checksum=$(shasum -a 256 ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz | awk '{print $1}')\n        fi\n        if [ \"$file_checksum\" != \"$expected_checksum\" ]; then\n            echo \"Checksum verification failed!\" >&2\n            exit 1\n        fi\n        file ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz\n    "
         if: '${{ ((matrix.os == ''macos'')) && ((matrix.arch == ''aarch64'')) }}'
       - id: 'step-3'
         name: 'Setup JBR 21 for macOS AArch64'
@@ -117,7 +117,7 @@ jobs:
         with:
           java-version: '21'
           distribution: 'jdkfile'
-          jdkFile: '${{ runner.temp }}/jbr21.tar.gz'
+          jdkFile: '~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz'
         env:
           GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
         if: '${{ ((matrix.os == ''macos'')) && ((matrix.arch == ''aarch64'')) }}'
