fix checksum

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -164,7 +164,34 @@ jobs:
         if: '${{ ((matrix.os == ''macos'')) && (!(matrix.selfHosted)) }}'
       - id: 'step-4'
         name: 'Get JBR 21 for macOS AArch64'
-        run: "\n        checksum_url=\"https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz.checksum\"\n        checksum_file=\"checksum.tmp\"\n        wget -q -O $checksum_file $checksum_url\n\n        expected_checksum=$(awk '{print $1}' $checksum_file)\n        file_checksum=\"\"\n        \n        if [ -f ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz ]; then\n            file_checksum=$(shasum -a 512 ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz | awk '{print $1}')\n        fi\n        \n        if [ \"$file_checksum\" != \"$expected_checksum\" ]; then\n            wget -q --tries=3 https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz -O ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz\n            file_checksum=$(shasum -a 512 ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz | awk '{print $1}')\n        fi\n        \n        if [ \"$file_checksum\" != \"$expected_checksum\" ]; then\n            echo \"Checksum verification failed!\" >&2\n            rm -f $checksum_file\n            exit 1\n        fi\n        \n        rm -f $checksum_file\n        file ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz\n    "
+        run: |-
+          # Expand jbrLocationExpr if it contains ~
+          jbr_location_expr=$(eval echo ~/Downloads/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz)
+          
+          checksum_url="https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz.checksum"
+          checksum_file="checksum.tmp"
+          wget -q -O $checksum_file $checksum_url
+          
+          expected_checksum=$(awk '{print $1}' $checksum_file)
+          file_checksum=""
+          
+          if [ -f "$jbr_location_expr" ]; then
+              file_checksum=$(shasum -a 512 "$jbr_location_expr" | awk '{print $1}')
+          fi
+          
+          if [ "$file_checksum" != "$expected_checksum" ]; then
+              wget -q --tries=3 https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-21.0.5-osx-aarch64-b631.8.tar.gz -O "$jbr_location_expr"
+              file_checksum=$(shasum -a 512 "$jbr_location_expr" | awk '{print $1}')
+          fi
+          
+          if [ "$file_checksum" != "$expected_checksum" ]; then
+              echo "Checksum verification failed!" >&2
+              rm -f $checksum_file
+              exit 1
+          fi
+          
+          rm -f $checksum_file
+          file "$jbr_location_expr"
         if: '${{ ((matrix.os == ''macos'')) && ((matrix.arch == ''aarch64'')) }}'
       - id: 'step-5'
         name: 'Setup JBR 21 for macOS AArch64'
